# Generated by Django 4.1.2 on 2022-11-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomerPredict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Gender", models.CharField(default="", max_length=30)),
                (
                    "Married",
                    models.CharField(
                        choices=[("Yes", "Yes"), ("No", "No")],
                        default="",
                        max_length=100,
                    ),
                ),
                (
                    "Dependents",
                    models.CharField(
                        choices=[("0", "0"), ("1", "1"), ("2", "2"), ("3+", "3+")],
                        default="",
                        max_length=100,
                    ),
                ),
                (
                    "Education",
                    models.CharField(
                        choices=[
                            ("Graduate", "Graduate"),
                            ("Not Graduate", "Not Graduate"),
                        ],
                        default="",
                        max_length=100,
                    ),
                ),
                (
                    "Self_Employed",
                    models.CharField(
                        choices=[("Yes", "Yes"), ("No", "No")],
                        default="",
                        max_length=100,
                    ),
                ),
                ("Applicant_Income", models.PositiveIntegerField(default=0)),
                ("Coapplicant_Income", models.PositiveIntegerField(default=0)),
                ("Loan_Amount", models.PositiveIntegerField(default=0)),
                ("Loan_Amount_Term", models.PositiveIntegerField(default=0)),
                (
                    "Credit_History",
                    models.PositiveIntegerField(
                        choices=[("0", "0"), ("1", "1")], default=0
                    ),
                ),
                (
                    "Property_Area",
                    models.CharField(
                        choices=[("Yes", "Yes"), ("No", "No")],
                        default="",
                        max_length=100,
                    ),
                ),
            ],
        ),
    ]
