# Generated by Django 4.1.2 on 2022-11-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predict", "0002_alter_customerpredict_property_area"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerpredict",
            name="Gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female")],
                default="",
                max_length=30,
            ),
        ),
    ]
