# Generated by Django 4.1.2 on 2022-11-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predict", "0003_alter_customerpredict_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerpredict",
            name="Credit_History",
            field=models.PositiveIntegerField(choices=[(0, 0), (1, 1)], default=0),
        ),
    ]
