# Generated by Django 4.1.2 on 2022-11-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predict", "0004_alter_customerpredict_credit_history"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerpredict",
            name="Dependents",
            field=models.CharField(
                choices=[("0", 0), ("1", 1), ("2", 2), ("3+", 3)],
                default="",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="customerpredict",
            name="Education",
            field=models.CharField(
                choices=[("Graduate", 1), ("Not Graduate", 0)],
                default="",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="customerpredict",
            name="Gender",
            field=models.CharField(
                choices=[("Male", 0), ("Female", 1)], default="", max_length=30
            ),
        ),
        migrations.AlterField(
            model_name="customerpredict",
            name="Married",
            field=models.CharField(
                choices=[("Yes", 1), ("No", 0)], default="", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="customerpredict",
            name="Property_Area",
            field=models.CharField(
                choices=[("Urban", 1), ("Semiurban", 1), ("Rural", 0)],
                default="",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="customerpredict",
            name="Self_Employed",
            field=models.CharField(
                choices=[("Yes", 1), ("No", 0)], default="", max_length=100
            ),
        ),
    ]
