# Generated by Django 4.1.2 on 2022-11-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predict", "0007_alter_customerpredict_dependents_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerpredict",
            name="Married",
            field=models.CharField(
                choices=[(1, "Yes"), (1, "No")], default="", max_length=100
            ),
        ),
    ]
