# Generated by Django 4.1.2 on 2022-11-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predict", "0008_alter_customerpredict_married"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerpredict",
            name="Married",
            field=models.IntegerField(choices=[(1, "Yes"), (1, "No")], default=""),
        ),
    ]
