# Generated by Django 4.1.2 on 2022-11-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predict", "0009_alter_customerpredict_married"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerpredict",
            name="Credit_History",
            field=models.PositiveIntegerField(choices=[(1, 0), (1, 1)], default=0),
        ),
        migrations.AlterField(
            model_name="customerpredict",
            name="Dependents",
            field=models.IntegerField(
                choices=[(1, "0"), (1, "1"), (1, "2"), (1, "3+")], default=""
            ),
        ),
        migrations.AlterField(
            model_name="customerpredict",
            name="Education",
            field=models.IntegerField(
                choices=[(1, "Graduate"), (1, "Not Graduate")], default=""
            ),
        ),
        migrations.AlterField(
            model_name="customerpredict",
            name="Gender",
            field=models.IntegerField(choices=[(1, "Male"), (1, "Female")], default=""),
        ),
        migrations.AlterField(
            model_name="customerpredict",
            name="Property_Area",
            field=models.IntegerField(
                choices=[(1, "Urban"), (1, "Semiurban"), (1, "Rural")], default=""
            ),
        ),
        migrations.AlterField(
            model_name="customerpredict",
            name="Self_Employed",
            field=models.IntegerField(choices=[(1, "Yes"), (1, "No")], default=""),
        ),
    ]
