# Generated by Django 4.1.2 on 2022-11-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predict", "0011_alter_customerpredict_credit_history_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerpredict",
            name="Education",
            field=models.IntegerField(
                choices=[(0, "Graduate"), (1, "Not Graduate")], default=""
            ),
        ),
        migrations.AlterField(
            model_name="customerpredict",
            name="Gender",
            field=models.IntegerField(choices=[(1, "Male"), (0, "Female")], default=""),
        ),
        migrations.AlterField(
            model_name="customerpredict",
            name="Property_Area",
            field=models.IntegerField(
                choices=[(2, "Urban"), (1, "Semiurban"), (0, "Rural")], default=""
            ),
        ),
    ]
