# Generated by Django 4.1.2 on 2022-11-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predict", "0012_alter_customerpredict_education_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerpredict",
            name="Credit_History",
            field=models.PositiveIntegerField(
                choices=[(0.0, "0.0"), (1.0, "1.0")], default=0
            ),
        ),
    ]
