# Generated by Django 4.1.2 on 2022-11-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predict", "0013_alter_customerpredict_credit_history"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerpredict",
            name="Credit_History",
            field=models.IntegerField(choices=[(0.0, "0.0"), (1.0, "1.0")], default=0),
        ),
    ]
