# Generated by Django 4.1.2 on 2022-11-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predict", "0014_alter_customerpredict_credit_history"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerpredict",
            name="Loan_Amount",
            field=models.FloatField(default=0),
        ),
    ]
