# Generated by Django 4.1.2 on 2022-11-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predict", "0015_alter_customerpredict_loan_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerpredict",
            name="Credit_History",
            field=models.FloatField(choices=[(0.0, "0.0"), (1.0, "1.0")], default=""),
        ),
        migrations.AlterField(
            model_name="customerpredict",
            name="Loan_Amount",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
