# Generated by Django 4.1.2 on 2022-10-17 09:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="loan_amortization",
            fields=[
                (
                    "amortization_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("payment_amount", models.PositiveIntegerField(default=0)),
                ("interest_payment", models.PositiveIntegerField(default=0)),
                ("principal_paid", models.PositiveIntegerField(default=0)),
                ("remaining_balance", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="loan_application",
            fields=[
                (
                    "application_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "control_number",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "mode_of_payment",
                    models.CharField(
                        choices=[
                            ("Over the Counter", "Over the Counter"),
                            ("Bank Transfer", "Bank Transfer"),
                            ("Salary Deduction", "Salary Deduction"),
                        ],
                        default="",
                        max_length=200,
                    ),
                ),
                ("loan_amount", models.PositiveIntegerField(default=0)),
                ("loan_duration", models.PositiveIntegerField(default=0)),
                ("purpose", models.TextField()),
                (
                    "loan_status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Accepted", "Accepted"),
                            ("Rejected", "Rejected"),
                        ],
                        default="",
                        max_length=200,
                    ),
                ),
                ("remarks", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="loan_payment",
            fields=[
                (
                    "loan_payment_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "payment_reference_number",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("payment_amount", models.PositiveIntegerField(default=0)),
                ("proof_of_payment", models.FileField(upload_to="docs")),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Accepted", "Accepted"),
                            ("Rejected", "Rejected"),
                        ],
                        default="",
                        max_length=200,
                    ),
                ),
                ("comments", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="loan_type",
            fields=[
                (
                    "loan_type_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("loan_name", models.CharField(max_length=250)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="sms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "api_code",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("api_password", models.CharField(max_length=30)),
                ("api_status", models.CharField(max_length=100)),
                ("message", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="sms_log",
            fields=[
                (
                    "sms_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("sent_date", models.DateField(auto_now_add=True)),
                ("message", models.TextField()),
            ],
        ),
    ]
