# Generated by Django 4.1.2 on 2022-10-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0003_alter_loan_application_loan_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan_application",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="loan_payment",
            name="comments",
            field=models.TextField(blank=True, null=True),
        ),
    ]
