# Generated by Django 4.1.2 on 2022-10-30 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("loans", "0008_alter_loan_application_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan_amortization",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default="",
                limit_choices_to={"is_staff": False},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_amortization",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="loan_payment",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default="",
                limit_choices_to={"is_staff": False},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_payment",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
